# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:osx:
    cmds:
      - go build -o bin/osx/appdirs  ./cli/main.go

  build:linux:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o bin/linux/appdirs  ./cli/main.go

  deploy:linux:
    cmds:
      - task: build:linux
      - scp ./bin/linux/appdirs digitalocean:/home/mark
